// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMSvcqzqxZancPRi1ksWTd2u9Cz7nJi3c',
    appId: '1:79015291121:web:5fea819a610e6d27456150',
    messagingSenderId: '79015291121',
    projectId: 'pet-care-app-f100a',
    authDomain: 'pet-care-app-f100a.firebaseapp.com',
    storageBucket: 'pet-care-app-f100a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8To7lIxV1tmFDbU6rRprIht0CW_hqfk',
    appId: '1:79015291121:android:b9cd7f62f95953d3456150',
    messagingSenderId: '79015291121',
    projectId: 'pet-care-app-f100a',
    storageBucket: 'pet-care-app-f100a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACMqmE8hh91W3-pBHdu56h8Kn6tql1ESM',
    appId: '1:79015291121:ios:b4090cf5686dc7e2456150',
    messagingSenderId: '79015291121',
    projectId: 'pet-care-app-f100a',
    storageBucket: 'pet-care-app-f100a.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACMqmE8hh91W3-pBHdu56h8Kn6tql1ESM',
    appId: '1:79015291121:ios:b4090cf5686dc7e2456150',
    messagingSenderId: '79015291121',
    projectId: 'pet-care-app-f100a',
    storageBucket: 'pet-care-app-f100a.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMSvcqzqxZancPRi1ksWTd2u9Cz7nJi3c',
    appId: '1:79015291121:web:81d37cf2be9d3d57456150',
    messagingSenderId: '79015291121',
    projectId: 'pet-care-app-f100a',
    authDomain: 'pet-care-app-f100a.firebaseapp.com',
    storageBucket: 'pet-care-app-f100a.firebasestorage.app',
  );
}
